[package]
name = "soyboy-sp"
version = "0.5.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
edition = "2021"
description = "A VST3 instrument to make some chiptunes"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]

[dependencies]
vst3-sys = { branch = "feature/null-shared-vst-ptr", git = "https://github.com/t-sin/vst3-sys" }
vst3-com = { branch = "feature/null-shared-vst-ptr", git = "https://github.com/t-sin/vst3-sys" }

# workarround for parent window
egui_glow = { git = "https://github.com/t-sin/egui" }
glutin = { git = "https://github.com/t-sin/glutin" }

egui_extras = { git = "https://github.com/t-sin/egui", features = ["image"] }
image = { version = "0.24", features = ["png"] }

num = "0.4.0"
rand = "0.8.4"
widestring = "0.4.0"
