[package]
name = "soyboy-sp"
version = "0.5.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
edition = "2021"
description = "A VST3 instrument to make some chiptunes"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]

[dependencies]
vst3-sys = { version = "0.1.0", git = "https://github.com/RustAudio/vst3-sys" }
vst3-com = { version = "0.1.0", git = "https://github.com/RustAudio/vst3-sys" }

# workarround for parent window
egui_glow = { git = "https://github.com/t-sin/egui", features = ["winit"] }
glutin = { git = "https://github.com/t-sin/glutin" }

rand = "0.8.4"
widestring = "0.4.0"
